[package]
name = "omni-cmd"
version = "0.1.0"
edition = "2021"
description = "Print information about an OmniOS machine."

[[bin]]
name = "omni"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
indexmap = "2.2.6"
nix = { version = "0.29.0", features = ["hostname", "fs"] }
zonename = "0.1.1"
